name: sdk_chat_remarked
description: "Chat SDK for Remarked"
version: 0.3.30+34
homepage: https://github.com/zorro112233/sdk_chat_remarked
repository: https://github.com/zorro112233/sdk_chat_remarked

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  animate_do: ^4.2.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  freezed_annotation: ^3.0.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  logging: ^1.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  web_socket_channel: ^3.0.2
  json_annotation: ^4.9.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.3
  json_serializable: ^6.9.4
  build_runner: ^2.4.15

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  uses-material-design: true
  assets:
    - packages/sdk_chat_remarked/assets/images/arrow-left.png
    - packages/sdk_chat_remarked/assets/images/chat.png
    - packages/sdk_chat_remarked/assets/images/readed.png


  fonts:
    - family: Inter
      fonts:
        - asset: packages/sdk_chat_remarked/assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: packages/sdk_chat_remarked/assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: packages/sdk_chat_remarked/assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: packages/sdk_chat_remarked/assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: packages/sdk_chat_remarked/assets/fonts/Inter-Light.ttf
          weight: 300
