name: sdk_chat_remarked
description: "A new Flutter package project."
version: 0.0.12+9
homepage: https://github.com/flutter/packages

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  logging: ^1.2.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
# /Users/nsvetlakov/.pub-cache/git/sdk_chat_remarked-972d99e917a714510b695521d4ba82e2b7658cae/lib/assets/images/chat.png
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - packages/sdk_chat_remarked/assets/images/arrow-left.png
    - packages/sdk_chat_remarked/assets/images/chat.png
    - packages/sdk_chat_remarked/assets/images/readed.png


  fonts:
    - family: Inter
      fonts:
        - asset: packages/sdk_chat_remarked/assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: packages/sdk_chat_remarked/assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: packages/sdk_chat_remarked/assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: packages/sdk_chat_remarked/assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: packages/sdk_chat_remarked/assets/fonts/Inter-Light.ttf
          weight: 300
