name: sdk_chat_remarked
description: "Chat SDK for Remarked"
version: 0.1.20+20
homepage: https://github.com/zorro112233/sdk_chat_remarked
repository: https://github.com/zorro112233/sdk_chat_remarked

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  animate_do: ^3.3.4
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.3.0
  freezed_annotation: ^2.4.4
  image_picker: ^1.1.2
  intl: ^0.19.0
  logging: ^1.2.0
  path: ^1.9.0
  path_provider: ^2.1.4
  web_socket_channel: ^3.0.1
  json_annotation: ^4.9.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  uses-material-design: true
  assets:
    - packages/sdk_chat_remarked/assets/images/arrow-left.png
    - packages/sdk_chat_remarked/assets/images/chat.png
    - packages/sdk_chat_remarked/assets/images/readed.png


  fonts:
    - family: Inter
      fonts:
        - asset: packages/sdk_chat_remarked/assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: packages/sdk_chat_remarked/assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: packages/sdk_chat_remarked/assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: packages/sdk_chat_remarked/assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: packages/sdk_chat_remarked/assets/fonts/Inter-Light.ttf
          weight: 300
